class Actions:
    IDLE = 0
    BLOCK = 1
    DODGE_LEFT = 2
    DODGE_RIGHT = 3
    PREP_PUNCH_LEFT = 4
    PREP_PUNCH_RIGHT = 5
    PUNCH_LEFT = 6
    PUNCH_RIGHT = 8
    PUNCHED_LEFT = 9
    PUNCHED_RIGHT = 10

    DECISIONS = (IDLE, BLOCK, DODGE_LEFT, DODGE_RIGHT, PUNCH_LEFT, PUNCH_RIGHT)